### ISSUE TITLE
When taking the template, the action start directly but fails

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#14]
As identified by @rlanzafame 

See here: https://github.com/TeachBooks/test/actions/runs/8844316408/job/24285981641
I think it's because github pages wasn't activated. In the second attempt I activated it and then it worked: https://github.com/TeachBooks/test/actions/runs/8844316408

**Comment by Tom-van-Woudenberg** [comment]
Can we enable it from the action itself? https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#configuring-the-configure-pages-action

**Comment by severinbratus** [comment]
I have tried it, it did not work out. I think we should move on and simply state in our docs that the first automatic pipeline will always fail, since Pages have to be enabled. I assume it's OK to close ?
