### ISSUE TITLE
typo in status report

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/deploy-book-workflow#28]
See screenshot, there may be a typo in the report that causes the Markdown code format to not work.

The screenshot is from [this run](https://github.com/TeachBooks/exploratory_computing_with_python/actions/runs/9240668487)

![image](https://github.com/TeachBooks/deploy-book-workflow/assets/22560680/96089454-afc0-48a2-acc2-77365926f86e)

**Comment by Tom-van-Woudenberg** [comment]
@severinbratus , could you fix this? The other issues are long term issues
