### ISSUE TITLE
display code as multiline in preview of errors and warnings

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/deploy-book-workflow#29]
The error report is on multiline, but the summary only displays one line, making it difficult to read.

The example below shows how the copy/paste works fine to preserve newlines, but the markup display does not

[example failed job](https://github.com/TeachBooks/mbakker_exploratory_computing/actions/runs/9240668487)

```
/home/runner/work/_temp/6b132ec8-1825-4122-af8b-89d07b523bdc.sh: /home/runner/work/exploratory_computing_with_python/exploratory_computing_with_python/.venv/bin/teachbooks: /home/runner/work/mbakker_exploratory_computing/mbakker_exploratory_computing/.venv/bin/python: bad interpreter: No such file or directory
```

![image](https://github.com/TeachBooks/deploy-book-workflow/assets/22560680/75b6ef81-c4aa-422f-ac3e-10dedde7fe44)

**Comment by rlanzafame** [comment]
Ahhhhh, now i notice that the raw text that is copied has the newline, but it's only the GitHub markup that is not displaying properly. So my example above is flawed.

Anyway, maybe this is more trouble than it is worth (in which case perhaps a simple note of "copy/paste the error summary into a text editor to see line breaks" or something similar would be sufficient

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame
The link to the action is pointing to the wrong action summary, I don't see the issue there.
The error thing does support multiline errors. In your example the actual error is oneline in the GitHub 'CLI' itself.
So I think we can close this one

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame
The link to the action is pointing to the wrong action summary, I don't see the issue there.
The error thing does support multiline errors. In your example the actual error is oneline in the GitHub 'CLI' itself.
So I think we can close this one
