### ISSUE TITLE
Define branches to be stripped with --published in variable 

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#3]
As the root branch might not be the only one which should have chapters stripped out

**Comment by Tom-van-Woudenberg** [comment]
As discussed with @rlanzafame

**Comment by severinbratus** [comment]
I have some questions on the special cases. I assume:
1. if the config var is undefined, we only preprocess the primary branch;
2. if equal to space, we preprocess none.

**Comment by Tom-van-Woudenberg** [comment]
If undefined, preprocess none

**Comment by Tom-van-Woudenberg** [comment]
> I have some questions on the special cases. I assume:
> 1. if the config var is undefined, we only preprocess the primary branch;
No, let's do no preprocessing in that case 
> 2. if equal to space, we preprocess none.
Yes
