### ISSUE TITLE
workflow breaks when repository name changes

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/deploy-book-workflow#30]
I changed the name of a repository and the Actions workflow failed

An example is below, but it is simple to recreate this issue:
- Setting > General > "Repository Name" field is altered
- Initiate a new job

[example job](https://github.com/TeachBooks/mbakker_exploratory_computing/actions/runs/9240668487)

```
/home/runner/work/_temp/6b132ec8-1825-4122-af8b-89d07b523bdc.sh: /home/runner/work/exploratory_computing_with_python/exploratory_computing_with_python/.venv/bin/teachbooks: /home/runner/work/mbakker_exploratory_computing/mbakker_exploratory_computing/.venv/bin/python: bad interpreter: No such file or directory
```

**Comment by Tom-van-Woudenberg** [comment]
I think the issue arrises because you take the cached virtual environment which has the repo name in it, but then try to execute it from the dir with the new repo name

**Comment by rlanzafame** [comment]
i agree. but i don't know how to fix it - if it is time consuming to address, we can skip it.
