### ISSUE TITLE
Allow for private repos

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#32]
Now it fails as can be seen here: https://github.com/TeachBooks/mirror_teachbook_manual/actions/runs/9254768881

**Comment by severinbratus** [comment]
If TeachBooks has the GH Free plan, deploying privates repos to GH Pages is not accessible: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

**Comment by Tom-van-Woudenberg** [comment]
Teachbooks has a GitHub Teams plan, so it should be possible :)

**Comment by Tom-van-Woudenberg** [comment]
> Teachbooks has a GitHub Teams plan, so it should be possible :)

But the workflow does fail because it cannot seem to clone the repository
