### ISSUE TITLE
If only one branch is build, put it only on root and don't copy it to /branch-name

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#33]
Could this be a simply one to do quick @severinbratus ?

Here's an example: https://github.com/TeachBooks/Showing-Physics/actions/runs/9268801649. Here I set the primary book at root to ' ' to make sure it's not copied (which is undesired because the book is very big). Would be nice if the behaviour would be such that if there's only one branch, it's build only on root by default.

**Comment by Tom-van-Woudenberg** [comment]
The general idea should be, keep the build book artifact as small as possible

**Comment by Tom-van-Woudenberg** [comment]
Can be long term if it's hard to fix

**Comment by severinbratus** [comment]
With redirects #39 copying is disabled by default
