### ISSUE TITLE
Fix unknown error message

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#38]
as visible here: https://github.com/Contemporary-Physicslab/Demolab/actions/runs/9497887872

I suspect that there are so many building warning in the process that the summary artifact became too large. How did you solve it @FreekPols?

**Comment by FreekPols** [comment]
Fix bugs... had broken reference to figure in 150 documents, taht was probably the problem.

**Comment by severinbratus** [comment]
The limit is documented here: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs (A job's outputs cannot exceed 1MB). @Tom-van-Woudenberg I think you are probably right. To close this issue, I suppose the best we can do is to include a special message in the summary when this happens.
