### ISSUE TITLE
Error message shows up to often

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#44]
@severinbratus, the message from #41  now shows up too often:
- https://github.com/TeachBooks/bridging_mechanics/actions/runs/9542669432
- https://github.com/TeachBooks/testable-template/actions/runs/9536726675

**Comment by severinbratus** [comment]
Should be now fixed by https://github.com/TeachBooks/deploy-book-workflow/commit/494bec28c91865055fddf2af07e21b58722d3ff8
