### ISSUE TITLE
Allow workflow to workflow to work for private personal repo's

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#47]
I think this should be possible, but it doesn't work at this moment (only if the private repo is part of an organization):
![image](https://github.com/TeachBooks/deploy-book-workflow/assets/122541126/9de5a96a-e37c-4c39-bf36-8b1a22661b7a)

@FreekPols, FYI

**Comment by severinbratus** [comment]
Closed by #48
