### ISSUE TITLE
change name of build status in workflow summary

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/deploy-book-workflow#52]

**Comment by rlanzafame** [comment]
seems like all examples here can simply be changed to "Release(d)"
![Image](https://github.com/user-attachments/assets/8976e54f-6d15-4ac2-94a7-81ce4d42d1a5)

**Comment by rlanzafame** [comment]
actually - maybe "Successful" is a better build status (regardless of publish/release). Maybe a whole legend overhaul, what about this?
- Successful - new version released online.
- Build failed [1] - previous release of book reused.
- Build failed [2] - no previous release used.

for the last one - is it also true that then there is no book at that URL? If so, add "No release online."

**Comment by Tom-van-Woudenberg** [comment]
Done
