### ISSUE TITLE
Rebuilding book instead of using cached version

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#8]
As discussed with @severinbratus before but without example, now it happened again:
After this commit: https://github.com/TeachBooks/engineering-systems-optimization/commit/7f453d2dc6dbf399259344d6090b49d37e9c4ed6 the workflow built both branches, while only the `2023` branch was updated. Not a big issue because the build is done in parallel

**Comment by severinbratus** [comment]
I could not find the cause -- I suppose this is because GitHub's cache is not perfect -- it might not save *everything* it has built. In my view, we can close this issue, until (if at all) this becomes an obstacle

**Comment by Tom-van-Woudenberg** [comment]
Sure!
